<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [spe-dev] Open workspace: crash
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/python-spe-dev/2007-April/index.html" >
   <LINK REL="made" HREF="mailto:python-spe-dev%40lists.berlios.de?Subject=Re%3A%20%5Bspe-dev%5D%20Open%20workspace%3A%20crash&In-Reply-To=%3C1B6972B5-5D8E-470A-8BDE-304DFBD4B1F4%40yahoo.co.uk%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000296.html">
   <LINK REL="Next"  HREF="000298.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[spe-dev] Open workspace: crash</H1>
    <B>Pietje Puk</B> 
    <A HREF="mailto:python-spe-dev%40lists.berlios.de?Subject=Re%3A%20%5Bspe-dev%5D%20Open%20workspace%3A%20crash&In-Reply-To=%3C1B6972B5-5D8E-470A-8BDE-304DFBD4B1F4%40yahoo.co.uk%3E"
       TITLE="[spe-dev] Open workspace: crash">pietjepuk314 at yahoo.co.uk
       </A><BR>
    <I>Tue Apr 24 09:38:08 CEST 2007</I>
    <P><UL>
        <LI>Previous message: <A HREF="000296.html">[spe-dev] Trouble with berlios.de?
</A></li>
        <LI>Next message: <A HREF="000298.html">[spe-dev] Open workspace: crash
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#297">[ date ]</a>
              <a href="thread.html#297">[ thread ]</a>
              <a href="subject.html#297">[ subject ]</a>
              <a href="author.html#297">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>There seems to be a bug in open_workspace, with closing the dialog  
box when there is an exception. (I don't know where this exception  
occurs, nor what it is.)
The bug must be in Parent.py, in the Panel class.

I tried to fix it using a try...finally block, as follows:

     def open_workspace(self):
         &quot;&quot;&quot;Open file dialog.&quot;&quot;&quot;
         try:
             defaultDir=info.dirname(self.workspace['file'])
         except:
             defaultDir=''
         try:
             dlg = wx.FileDialog(self, &quot;Choose a file - www.stani.be&quot;,
                 defaultDir=defaultDir, defaultFile=&quot;&quot;,
                 wildcard=info.WORKSPACE_WILDCARD,
                 style=wx.OPEN)
             if dlg.ShowModal() == wx.ID_OK:
                 file = dlg.GetPath()
                 try:                    self.set 
(&quot;currentworkspace&quot;,file)
                     self.__openWorkspace__()
                     self.loadWorkspace()
                 except Exception,e:
                     self.message(&quot;Could not open workspace:%s\n%s&quot;% 
(file,e))
         finally:
             dlg.Destroy()

and, just to be sure, I did save_workspace too, where I found a like  
bug earlier:
     def save_workspace_as(self):
         &quot;&quot;&quot;Save file dialog.&quot;&quot;&quot;
         try:
             defaultFile = self.workspace['file']
         except:
             defaultFile = ''        if info.WIN:
            defaultFile  = defaultFile.replace(&quot;/&quot;,&quot;\\&quot;)
         try:
             dlg             = wx.FileDialog(self, &quot;Save Workspace As  
- www.stani.be&quot;,
                 defaultFile = defaultFile,
                 defaultDir  = info.dirname(defaultFile),
                 wildcard    = info.WORKSPACE_WILDCARD,
                 style       = wx.SAVE|wx.OVERWRITE_PROMPT| 
wx.CHANGE_DIR)
             if dlg.ShowModal() == wx.ID_OK:
                 file = dlg.GetPath()
                 try:
                     self.set(&quot;currentworkspace&quot;,file)
                     self.saveWorkspace(file)
                 except Exception,e:
                     self.message(&quot;Could not save workspace:%s\n%s&quot;% 
(file,e))
         finally:
             dlg.Destroy()

The effect is that I can open a workspace, and that everything looks  
fine, but then all of a sudden it shows *another* file dialog! On  
clicking cancel, SPE goes down in a bang.
Reopening it gives the correct new workspace, however.
I am running SPE, latest checkout plus above changes, on a MacBook Pro.

Any ideas?
- Jurjen

	
	
		
___________________________________________________________ 
All new Yahoo! Mail &quot;The new Interface is stunning in its simplicity and ease of use.&quot; - PC Magazine 
<A HREF="http://uk.docs.yahoo.com/nowyoucan.html">http://uk.docs.yahoo.com/nowyoucan.html</A>

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000296.html">[spe-dev] Trouble with berlios.de?
</A></li>
	<LI>Next message: <A HREF="000298.html">[spe-dev] Open workspace: crash
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#297">[ date ]</a>
              <a href="thread.html#297">[ thread ]</a>
              <a href="subject.html#297">[ subject ]</a>
              <a href="author.html#297">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/python-spe-dev">More information about the Python-spe-dev
mailing list</a><br>
</body></html>
